### ISSUE TITLE
Package bug 🐛

### ISSUE THREAD

**Issue by Kaito1108** [bpisano/Sticker#1]
I've seen your post.👀
I thought it was very nice and tried to include it, but there's a bug in it.

![CleanShot 2024-11-13 at 23 09 18](https://github.com/user-attachments/assets/00e666fc-dbcd-4194-8697-79970f01d73d)

I have a bug in the following code, can you fix it?

```
import SwiftUI
import Sticker

struct ContentView: View {
    var body: some View {
        VStack {
            Image(systemName: "bolt.fill")
                .stickerEffect()
                .stickerMotionEffect(.pointerHover(intensity: 0.5))
        }
    }
}

#Preview {
    ContentView()
}

```

Sorry if my code is wrong. 🙇

**Comment by Kaito1108** [comment]
@bpisano

**Comment by bpisano** [comment]
Hi @Kaito1108 👋 what platform and version are you targeting? This package is only available on the following platforms:
```swift
platforms: [
    .iOS(.v17),
    .macOS(.v14),
    .visionOS(.v1)
]
```

**Comment by Kaito1108** [comment]
macOS: 14.3.1
Maybe it'll work.🧐

**Comment by Kaito1108** [comment]
@bpisano

**Comment by bpisano** [comment]
I don't have a Mac running macOS 14 anymore. But I tried on iOS 17, which is the macOS version equivalent, and everything works on my side from a scratch project. Your issue looks like a version mismatch somewhere in your project. You need at least iOS 17, macOS 14 and visionOS 1. The minimum Swift version is set to 5.10.

**Comment by Kaito1108** [comment]
@bpisano 
Ok
Sorry for the short notice.
Thank you.😊
